### PR TITLE
Update tzlocal and allow compressed_rtf and ebcdic updates

### PR DESCRIPTION
**Pull request by reneleonhardt**
- [x] Issue #: (Replace text with #<issue_number>)
- [x] Have you listed any changes to install or build dependencies?
- [x] Ensured your changes are compatible with Python 2.7 (ONLY FOR v0.29).
- [x] Have you updated the [CHANGELOG](CHANGELOG.md) with details of changes to the codebase, this includes new functionality, deprecated features, or any other material changes.
- [x] If necessary, have you bumped the version number? We will usually do this for you.
- [x] Have you included py.test tests with your pull request. (Not yet necessary)
- [x] Ensured your code is as close to PEP 8 compliant as possible?
- [x] Ensured your pull request is to the `next-release` branch (or `v0.29` if applicable)?

If you haven't completed the above items, please wait to create a PR until you have done so. We will try to review and reply to PRs as quickly as possible.

Once your PR is approved by a maintainer, we will either merge it into next-release or do a release with you or for you.

Thanks for contributing!

### CODE REVIEW

**Comment by TheElementalOfDestruction** [comment]
Gonna have to deny this for several reasons:
1. Undocumented change in the commit (Not mentioned in the pull request nor the changelog, I had to discover it by looking in the commit details)
2. A previous commit suggested the update to red-black-tree-mod, which was denied for several reasons. You can see the pull request [here](https://github.com/TeamMsgExtractor/msg-extractor/pull/313). I'm actually looking to (and trying to work with someone) replace all usage of the module with something either smaller or better maintained that would be a direct part of the extract-msg package. Additionally, I know of exactly 0 other packages that actually depend on it, let alone a newer version of it. The update changed no functionality and, as far as I could tell, didn't change any of the code we actually use at all, and so provides no benefit to us over the new version, which has the problems discussed previously. If you actually know of a package requiring it, I'll look into updating the requirement, but the lack of semantic versioning means <2 is unacceptable.
3. You added another commit with more problematic versions (some of those packages do not follow semantic versioning and so cannot be guaranteed to have a compatible API within the versioning you have set. We would *hope* that they would, but cannot assure it).

That said, the update to tzlocal, compressed_rtf (doesn't specify semantic versioning, but it looks close enough), and ebcdic as well as the big fix you made are acceptable, so long as they are appropriately documented. If you fix these issues or can convince me they aren't issues, I'll accept the pull request

**Comment by reneleonhardt** [comment]
I updated most dependencies to allow other projects to update their dependency trees too.
Then I fixed the last PR, if you can, add tests for new functions and enable GitHub Actions to see if builds are failing.

**Comment by reneleonhardt** [comment]
I will try to revert what was too much by that definition.
If you want the poetry files I created to update everything where possible, let me know.

**Comment by TheElementalOfDestruction** [comment]
Unfortunately, I don't currently have the time to learn how github actions actually works, so I can't easily set it up. It's on my todo list for the future. Also, I'm not sure what a poetry file is, so I've added that to my todo list as well. For now I'll accept the commit and work on getting the next release out.

**Pull request merged**
