### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Rafiot**
There are typos in the versions for the dependencies and it makes poetry whine. The one thing you might ignore and/or check is the version of red-black-tree-mod which was updated for the first time in almost 10 years and there are no descriptions of the changes anywhere.

### CODE REVIEW

**Comment by TheElementalOfDestruction** [comment]
Given that the change happened literally the day after it became a requirement, I'm *very* suspicious about that change. In addition, I gave it a fixed version since I wasn't able to confirm the versioning system and whether it's api would remain stable.

**Comment by Rafiot** [comment]
Makes sense, I reverted that. For the other ones, it should be fine :)

**Comment by TheElementalOfDestruction** [comment]
I opened up the code for the version I specified and the new version and they look to be near identical despite one being significantly larger. With that change back and after changing to the right branch, things look fine so I'll see about getting a new release out for them soon.

**Comment by TheElementalOfDestruction** [comment]
Frankly the age, lack of versioning info, and the lack of a changelog means I'm not particularly attached to the module so long as I can find something that can handle red-black trees in as painless of a way for me as possible while being reasonably fast about it (I've not noticed anything major in terms of time consumption from the current module).

I guess if you know of a better maintained module that can do that, let me know and I'm happy to replace the current one.

**Pull request merged**
